### ISSUE TITLE
NullPointerException when you press Cancel when opening a file

### ISSUE THREAD

**Issue by bworrell** [STIXProject/java-stix-validator-DEPRECATED#3]
If you press the `Cancel` button on the "Load File..." dialog, a NullPointerException is thrown. This doesn't appear to alter the behavior of the application in any way, but you do see a large stack dump in the console window if the program was launched via `java -jar ...`.

**Comment by gtback** [comment]
Closing since this repository has been deprecated in favor of https://github.com/STIXProject/java-stix-validator.
