### ISSUE TITLE
GUI truncates messages and does not allow for exporting messages

### ISSUE THREAD

**Issue by thomsavage** [STIXProject/java-stix-validator-DEPRECATED#6]
Using the GUI here to validate a STIX file, I get a long message re: a problem in my file (which is legitimate). However, the message is too long for the single line in the results table, and I cannot extend the column long enough to see the full message.

There is also no obvious way to export the message out of the GUI (read: copy to clipboard).

![image](https://cloud.githubusercontent.com/assets/7690743/4394486/e9bba83e-4421-11e4-9eba-b623ded26e37.png)

**Comment by gtback** [comment]
Closing since this repository has been deprecated in favor of https://github.com/STIXProject/java-stix-validator.
